---
title: "insectary_comparison"
author: "Vish Dhokiya"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
```

Need three graphs showing temperature and humidity for CTGH (C) MKGH (MK) and ACPM1 (A)

Day 0 - 15 on the X axis and 0 - 100 on the y axs

```{r}

library(readxl)
C <- read_excel("Insectary Comparison.xlsx",   # Read in the relevant excel sheet 
    sheet = "TT CTIDGH", range = "A5:E1733", 
    col_types = c("text", "date", "numeric", 
        "numeric", "numeric"))

names(C)[2] <- "Date" # Assign the name Date to the second column

C <- C %>%
  mutate(Date = as.POSIXct(Date, format = "%Y-%m-%d %H:%M:%S")) # Change the data type for date to POSIXct 
  
  
 C$numeric_days <- as.numeric(C$Date) # this converts the posixct to a numerical format which is in seconds since a set time point
  
 C$numeric_days_since <- ((((C$numeric_days - 1685318640)/ 60)/60)/24) # this gives the seconds between the first time point for this insectary and each time point subsequently, and then converts this to days.
 
View(C)






MK <- read_excel("Insectary Comparison.xlsx", 
    sheet = "TT MKGH", range = "A5:E1733", 
    col_types = c("text", "date", "numeric", 
        "numeric", "numeric"))

names(MK)[2] <- "Date"

MK <- MK %>%
  mutate(Date = as.POSIXct(Date, format = "%Y-%m-%d %H:%M:%S"))
  
MK$numeric_days <- as.numeric(MK$Date)
  
 MK$numeric_days_since <- ((((MK$numeric_days - 1685319000)/ 60)/60)/24)

View(MK)






A <- read_excel("Insectary Comparison.xlsx", 
    sheet = "TT ACCPM1", range = "A5:E1733", 
    col_types = c("text", "date", "numeric", 
        "numeric", "numeric"))

names(A)[2] <- "Date"

A <- A %>%
  mutate(Date = as.POSIXct(Date, format = "%Y-%m-%d %H:%M:%S"))
 
A$numeric_days <- as.numeric(A$Date)
  
 A$numeric_days_since <- ((((A$numeric_days - 1685319240)/ 60)/60)/24)

View(A)

```



```{r}


 C_graph <- ggplot(data = C) + geom_line(aes(x = numeric_days_since, y = Temperature, color = "Temperature (°C)"), size = 1) + 
  
  geom_line(aes(x = numeric_days_since, y = Humidity, color = "Humidity (%RH)"), size = 1) +
  
  scale_y_continuous(limits = c(0, 100), breaks = seq(0,100, by = 10)) + scale_x_continuous(limits = c(0, 15), breaks = seq(0, 15, by = 1)) + 
  
  labs(x = "Day", y = NULL, color = NULL) + 
  
  theme_linedraw() +
  
  scale_color_manual(values = c("Temperature (°C)" = "#AC0123", "Humidity (%RH)" = "#7AA8D7")) +
  
  theme(axis.text = element_text(size = 12), axis.title = element_text(size = 14))

C_graph

```


```{r}

 A_graph <- ggplot(data = A) + geom_line(aes(x = numeric_days_since, y = Temperature, color = "Temperature (°C)"), size = 1) + 
  
  geom_line(aes(x = numeric_days_since, y = Humidity, color = "Humidity (%RH)"), size = 1) +
  
  scale_y_continuous(limits = c(0, 100), breaks = seq(0,100, by = 10)) + scale_x_continuous(limits = c(0, 15), breaks = seq(0, 15, by = 1)) + 
  
  labs(x = "Day", y = NULL, color = NULL) + 
  
  theme_linedraw() +
  
  scale_color_manual(values = c("Temperature (°C)" = "#AC0123", "Humidity (%RH)" = "#7AA8D7")) +
  
  theme(axis.text = element_text(size = 12), axis.title = element_text(size = 14))

A_graph

```


```{r}
 MK_graph <- ggplot(data = MK) + geom_line(aes(x = numeric_days_since, y = Temperature, color = "Temperature (°C)"), size = 1) + 
  
  geom_line(aes(x = numeric_days_since, y = Humidity, color = "Humidity (%RH)"), size = 1) +
  
  scale_y_continuous(limits = c(0, 100), breaks = seq(0,100, by = 10)) + scale_x_continuous(limits = c(0, 15), breaks = seq(0, 15, by = 1)) + 
  
  labs(x = "Day", y = NULL, color = NULL) + 
  
  theme_linedraw() +
  
  scale_color_manual(values = c("Temperature (°C)" = "#AC0123", "Humidity (%RH)" = "#7AA8D7")) +
  
  theme(axis.text = element_text(size = 12), axis.title = element_text(size = 14))
  
 

MK_graph

```




